### PR TITLE
the versionString = UNIVERSAL... gave an error due to 1.893.0 as example

### PR DESCRIPTION
**Pull request by reashetyrr**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: No current available issue present, this is found while working on fixing a bypass

While loading in linkvertise as example, i would always get an error thrown when injecting the script, with alot of debugging i found out that the versionString initialization was as fault, the UNIVERSAL_BYPASS_EXTERNAL_VERSION would be changed with something like 1.893.2 which would cause an javascript error.

it would be appended with an empty string making it a string, enclosing it in single quotes also makes it a string

- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [x] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by AliahX** [comment]
Appending a string to the end of a var makes the var a string, surrounding the var in quotes makes the string out of the vars name.

**Comment by reashetyrr** [comment]
> Appending a string to the end of a var makes the var a string, surrounding the var in quotes makes the string out of the vars name.

yes but `const some_number = 1.5.2 + ''` is invalid because of the second dot

**Comment by reashetyrr** [comment]
image
so because the versioning number ends up to have 2 dots it gave me an error

**Comment by NotAProton** [comment]
Thanks

**Pull request merged**
