### PR TITLE
Added bypass for ouo.io

### PR DESCRIPTION
**Pull request by RohanDebroy**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interests in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Example Link: https://ouo.io/ftUfZL (The destination is universal-bypass.org)

- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [x] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by NotAProton** [comment]
So, is this bypass outdated https://github.com/FastForwardTeam/FastForward/blob/2fe59b578d7fcce30ef344c695e1c9c7102f5975/src/js/injection_script.js#L963 ?

**Comment by RohanDebroy** [comment]
> So, is this bypass outdated
> 
> https://github.com/FastForwardTeam/FastForward/blob/2fe59b578d7fcce30ef344c695e1c9c7102f5975/src/js/injection_script.js#L963
> 
> ?


Here are the type of ouo links that I have ever encountered 
`https://ouo.io/*`
`https://ouo.io/go/*`
`https://ouo.press/*`
`https://ouo.press/go/*`

So if you used the older bypass method then it would have not worked for ouo URLs which do not have `/go/` in the pathname. 

Also, you can not directly add `/go/` to every ouo URL, doing so would directly redirect you to ouo homepage. You will only get `/go/` in the pathname only after visiting the shortened ouo URL and then submitting the captcha. But the new method does not require the captcha to be solved.

You can also try the example link with the older method and see it for yourself.

_Why I did not update the older code?_
Actually, I thought ouo uses the crowd bypass method only. So I didn't bother going through the source code otherwise I would have updated the older method.

Note:- Before I submitted the pull request I tested the older method. In my case **FastForward** was trying to use the crowd bypass method which was not working for me.

**Comment by RohanDebroy** [comment]
Hi, After thinking I have reverted those changes and will reopen this after making some modifications. Sorry for this.

**Comment by NotAProton** [comment]
np, pretty good for a first pull request. I was about to suggest using the ensureDomLoaded insertion point, but I see you're making progress by yourself : )

**Pull request closed without merging**
