### PR TITLE
added download.id && added adguard

### LINKED ISSUE #212: add download.id
### Domain

https://download.id/mozilla-firefox/

### Link

https://download.id/mozilla-firefox/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

please skip the download countdown at "download page", thanks

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #215: adguardteam anonymous redirect
### Domain

https://adguardteam.github.io

### Link

https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Link is from https://github.com/AdguardTeam/AdguardFilters/issues/92570

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PatchByte**
Hello there,
I am so sorry for the download.id code, but there is no other way to do that.
And it's directly going to the download link if you click on one of the download buttons!

Fixes: https://github.com/FastForwardTeam/FastForward/issues/215
Fixes: https://github.com/FastForwardTeam/FastForward/issues/212

### CODE REVIEW

**Comment by FinderID** [comment]
im sorry. So, the site can't be bypass?

sorry for my bad english, and thanks for your attention @PatchByte

**Comment by lem6ns** [comment]
> im sorry. So, the site can't be bypass?
> 
> sorry for my bad english, and thanks for your attention @PatchByte

The site can be bypassed, the bypass code itself doesn't look that clean though.

**Comment by PatchByte** [comment]
> im sorry. So, the site can't be bypass?
> 
> sorry for my bad english, and thanks for your attention @PatchByte

Well it's bypassed instead of going to the next website and waiting for it to redirect you,you can just click of any of the download button I am rewriting the link

**Comment by PatchByte** [comment]
> > im sorry. So, the site can't be bypass?
> > sorry for my bad english, and thanks for your attention @PatchByte
> 
> The site can be bypassed, the bypass code itself doesn't look that clean though.

Yeah because I want the fast way I just rewrite the buttons destination

**Comment by PatchByte** [comment]
image
I mean those buttons.
I basically rewrite the onclick script of them to the url that they would be going
the rewritten button code:
image

**Comment by PatchByte** [comment]
you can also see there is a hidden input that is the real url.
I am basically getting it and then rewriting the onclick function

**Comment by PatchByte** [comment]
@lem6ns

**Comment by NotAProton** [comment]
The adgaurd redirect is very similar to #200, can use regex there

**Comment by PatchByte** [comment]
> 

oof

**Comment by NotAProton** [comment]
Don't close it, you can just push commits to your branch to update your code

**Comment by PatchByte** [comment]
oh eh sorry

**Comment by PatchByte** [comment]
well i just checked on downloadfreecourse and if you want to download something you first go to a page that you then redirects to another page and then it will get bypassed.
So i added a bypass that it just redirects you through everything

**Comment by NotAProton** [comment]
You should make a separate for PR for downloadfreecourse

**Comment by NotAProton** [comment]
also, common practice is https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines
> Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
or "Fixes bug."

**Pull request closed without merging**
