### PR TITLE
feat: Add trib.al to trackers

### PR DESCRIPTION
**Pull request by 1fexd**
Fixes (Links to issues fixed by this PR): None

Description: Adds `trib.al` to tracker list

Checklist:

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [x] Tested on Firefox

### CODE REVIEW

**Comment by NotAProton** [comment]
Unshorten.me supports both, @1fexd please re open this PR for MV-3 (now the main branch)

**Comment by NotAProton** [comment]
This has a lot of conflicts it would be easier to close this PR and open a new one with the changes

**Comment by 1fexd** [comment]
Hm, does the tracker list make sense at all? Aren't there these huge lists out there?

**Comment by NotAProton** [comment]
We bypass tracker short links which lead somewhere, not cookies/adsense stuff (which uBlock origin does). Tracker links show a page like this when clicked on 
image

**Pull request closed without merging**
