### PR TITLE
Fix the bypass of acortalink.me

### PR DESCRIPTION
**Pull request by esponjosin**
Fixes (Links to issues fixed by this PR): #946 

Description: I simply did some reverse engineering after I was able to freeze the page and stop devtools from detecting and analyzing the code.

[Link for a fembed site](https://acortalink.me/s.php?i=VTJGc2RHVmtYMTlkUHlIL1ZCS2dmRlR3V1lKblU1TksvaG8wVzFnUmFpTkR4MzN4UEw1R2U1YUF4d2lIWERWTHhmYTE0Ync5SlRvMnZwMzhVay92Znc9PQ==)
[Link for a torrent](https://acortalink.me/s.php?i=VTJGc2RHVmtYMStXekhyNlgxdDVNM0laVVJFK1Q1VHg4WFVJekVpMFRsMjhVakxTUHY5SkNyNm5Gd3lLRkEvM3ppalp3emV1VHlaK3djd3B4VlhVOEhQaWlzN0VHRy8vN0RnQUZER2hyS3FQVnpsdGlSVEkwRW1aTEZPa3JIUkczYmorSXdvY2FUVjlsN3MyZEphUVlCaURpb3E2bEtPK3I0M0ljWUZpRnNvdHBiQW5xcHhGUVlaTXd4TU53V1haMFNkTDJMR0d4SEM1cUsxWG1BV1c2dnVmaTZWVW5MQjRmMUNMTmV1RnMrZHhCZ3FGb2hNMnpvNEQwOUg3Z2tWV05IcFc1Rk1nZGhhTzhVU0JzaVpzMWtXZU1NcFlzazJPQmlqclpqd0gvNEZsMmdDK3VtRUNNNS9VQ3MzNW1teEx3eER4Kys4WmNIU2lXS1NTTUFiOWVGamt2Q205Ky9KVTVjM1c2WWJzYVFMaCs4K3R5Y1lWS0Y3bER2SDFnSzd5S3RTRlhvRVFyS2lRcWVySzNWa2U5VjRMVHIyb1Avam1jYSt3clNpbVdpST0=)

Checklist:
- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

### CODE REVIEW

**Comment by ghost** [comment]
It always redirects me to google whenever I try to enter the link, maybe it's the bypassing method that's triggering the site?

**Comment by esponjosin** [comment]
> It always redirects me to google whenever I try to enter the link, maybe it's the bypassing method that's triggering the site?

Apparently the script starts after the ensureDomLoaded function is executed, I will try the awaitElement function,
And safelyNavigation does not detect the magnet:?xt which are texts for the torrents but it is understandable for the security of the user.

**Comment by ghost** [comment]
> > It always redirects me to google whenever I try to enter the link, maybe it's the bypassing method that's triggering the site?
> 
> Apparently the script starts after the ensureDomLoaded function is executed, I will try the awaitElement function, And safelyNavigation does not detect the magnet:?xt which are texts for the torrents but it is understandable for the security of the user.

Don't use awaitElement, you need to change the file so that ensureDomLoaded is NOT called so that the script can immediately execute. See if that works.

**Comment by esponjosin** [comment]
> > > It always redirects me to google whenever I try to enter the link, maybe it's the bypassing method that's triggering the site?
> > 
> > 
> > Apparently the script starts after the ensureDomLoaded function is executed, I will try the awaitElement function, And safelyNavigation does not detect the magnet:?xt which are texts for the torrents but it is understandable for the security of the user.
> 
> Don't use awaitElement, you need to change the file so that ensureDomLoaded is NOT called so that the script can immediately execute. See if that works.

Do you say how to use an interval and stop it when the script is found?

**Comment by ghost** [comment]
> Do you say how to use an interval and stop it when the script is found?

use setInterval

**Comment by esponjosin** [comment]
> > Do you say how to use an interval and stop it when the script is found?
> 
> use setInterval

I've already made the changes if you can try them, I'm waiting for your answer.

**Comment by ghost** [comment]
Sorry, it still looks like it is detecting it and going to google.

**Comment by ghost** [comment]
@esponjosin are you still willing to fix or should I close?

**Pull request closed without merging**
