### PR TITLE
add: vebma.com, fix: miuiku.com, sekilastekno.com

### PR DESCRIPTION
**Pull request by nfal001**
Fix(es): 

Add adtival.js for Adtival.network related shortlink domain. should fixed miuiku.com, sekilastekno.com, also add new bypass for vebma.com

- [x] I made sure there are no unnecessary changes in the code;
- [ ] Tested on Chromium (Includes Opera, Brave, Vivaldi, Edge, etc);
- [x] Tested on Firefox.

### CODE REVIEW

**Comment by nfal001** [comment]
forgot to add link samples:

- https://apk.miuiku.com/bLJaopKFF
- https://wp.sekilastekno.com/r/nXLxHAX2e
- https://info.vebma.com/r/oZNC7Dj8k

**Comment by reashetyrr** [comment]
it looks great, i will pull and test when im home, at worst this may be tomorrow :)

**Comment by ghost** [comment]
Make sure to add all the sites you've added into Bypassed.md

**Comment by nfal001** [comment]
sorry, i forgot to list adtival.network. all should be good after this commit, all sites added in adtival.js was already listed in Bypassed.md . but i can only verify miuiku and sekilastekno. can't verify other site listed, i don't have shortlink samples for it. the regex used came from old bypass, i assume that other site has similiar technique.

mentioned code:

https://github.com/FastForwardTeam/FastForward/blob/main/src/js/injection_script-original.js?plain=1#L1198

**Comment by driedpampas** [comment]
tested on chrome :sparkles:

**Pull request merged**
