### PR TITLE
Added a modular system for bypassing different linkvertise content types and added a paste bypass.

### PR DESCRIPTION
**Pull request by davidkra230**
\#### this is a continuation of #928, the reason is that i had messed something up with the fork and it did not show changes. ####

Fixes (Links to issues fixed by this PR): 
None

Description:
bypasses linkvertise's pasting feature. basically i just added a check for pastes and if it matches it will get the info almost exactly like the url bypass ~~except it copies the paste instead of redirecting~~ but it redirects to a blob url of the paste text.

Test links:
[LinkvertisePaste](https://linkvertise.com/114822/test?o=sharing)
Checklist:

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [x] Tested on Firefox

### CODE REVIEW

**Comment by davidkra230** [comment]
wait, i just noticed that the formatting is extremely messed up, lemme fix rq.

**Comment by davidkra230** [comment]
i keep messing things up
dang

**Comment by davidkra230** [comment]
bruh

**Comment by lem6ns** [comment]
third time's the charm :)

**Comment by davidkra230** [comment]
it didn't do anything because i was trying to squash the commits and failed, so i reverted and it didn't apply anything

**Pull request closed without merging**
