### PR TITLE
Fixed adshrink.it bypasser

### PR DESCRIPTION
**Pull request by SwitchAlpha**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: adshrink.it bypass fixed and adshnk.com bypass added

Changed link detection system.
Test Link: https://adshrink.it/kzYln2 (redirects google)
Test Link: https://adshnk.comt/kzYln2 (redirects google)

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by lostdusty** [comment]
Isn't this and #748 the same website?

**Comment by SwitchAlpha** [comment]
> Isn't this and #748 the same website?

They have same api but diffrent domain

**Comment by vincegiordano** [comment]
I find this to not consistently work. When I add FF it works. But then later when I open a new Chrome window it sometimes doesn't work. I have to remove FF and re-add for it to work again, but its only temporary.

**Comment by Asrum** [comment]
Slack.com

**Pull request merged**
