### PR TITLE
fox android fennec 68.11 and temp disable/remove linkvertize

### PR DESCRIPTION
**Pull request by kevin01523**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: Link to issue

- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [x] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by kevin01523** [comment]
Dont merge

**Comment by kevin01523** [comment]
I think linkvertize need to be reworked since its buggy

**Review by NotAProton — COMMENTED** [review]
https://www.mozilla.org/en-US/firefox/android/68.11.0/releasenotes/
I see no reason to support a year-old release which is not even receiving security updates. 

We are already supporting kiwi for android. https://github.com/FastForwardTeam/releases#kiwi-android

**Comment by kevin01523** [comment]
Well if possible a fix where not removing linkvertise is preferable.
There something is Bypass itself that kinda breaks stuff.ive encountered similar bugs on universal bypass before sainan did rework some bypass so the extension doesn't hang or crash

**Comment by NotAProton** [comment]
not merging this, will add re-writing linkvertise bypass to the todo list

**Pull request closed without merging**
