### PR TITLE
Add linkerload.com bypass (resolve #60)

### LINKED ISSUE #60: linkerload.com
### Domain

https://linkerload.com/in7XRr

### Link

https://linkerload.com/0LX7iVxFj

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lem6ns**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: #60 

Regex for duit.cc

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [x] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by NotAProton** [comment]
not working on my machine

```Uncaught SyntaxError: invalid arrow-function arguments (parentheses around the arrow-function may help)```

**Comment by lem6ns** [comment]
> 
> 
> not working on my machine
> 
> `Uncaught SyntaxError: invalid arrow-function arguments (parentheses around the arrow-function may help)`

Please try it again with the new fix

**Comment by NotAProton** [comment]
now its just not working

**Review by NotAProton — COMMENTED** [review]
```
ifElement("button.btn-fast-download", download => {
		download.click()
	    })
	    ifElement("#download", download => {
		download.firstChild.submit.click()
	    })
})
```

**Comment by NotAProton** [comment]
It just leads you to blank page
`https://linkerload.com/getlink.php`

**Comment by lem6ns** [comment]
> 
> 
> It just leads you to blank page
> `https://linkerload.com/getlink.php`

that's why the reload thing is there since it's unclean

**Comment by lem6ns** [comment]
closed until I find a cleaner duit bypass

**Pull request closed without merging**
