### PR TITLE
Revert "Update strings Portuguese Brazil"

### PR DESCRIPTION
**Pull request by lostdusty**
Reverts FastForwardTeam/FastForward#1177

### CODE REVIEW

**Comment by driedpampas** [comment]
wow already :sob:

**Comment by davbrasan** [comment]
Did you have any problems with my translation?

**Comment by lostdusty** [comment]
> Did you have any problems with my translation?

Yeah, I did a review on your translations

**Comment by davbrasan** [comment]
I used the messege.json file in English to translate, why is the current one out of date

**Pull request merged**
