### PR TITLE
Add bypass for allkeyshop.com

### PR DESCRIPTION
**Pull request by Smart123s**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: Link to issue

- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [x] Tested on Firefox

\* indicates required

This is my first contribution to FastForward. I tried looking at the code above mine to figure out how I should do things, but I'm still not sure if I had done everything right.

### CODE REVIEW

**Comment by NotAProton** [comment]
Have any example links of allkeyshop.com?

**Comment by Smart123s** [comment]
https://www.allkeyshop.com/blog/buy-the-last-campfire-cd-key-compare-prices/

Just click on one of the prices, and you should be redirected to something like this:
https://www.allkeyshop.com/outgoinglink/link/133022962?merchant=13

**Comment by Smart123s** [comment]
Also, I've got two questions:

- Should I use `safelyAssign` instead of `safelyNavigate`?
- Is `ensureDomLoaded()` needed here?

**Comment by NotAProton** [comment]
> Should I use safelyAssign instead of safelyNavigate

safelyNavigate, so that the user can preview the destination

> Is ensureDomLoaded() needed here?

It's already in ensureDomLoaded https://github.com/FastForwardTeam/FastForward/blob/01a466d4ea89d26d84381dac5226fc4c69e9e093/src/js/injection_script.js#L887

**Comment by NotAProton** [comment]
Thanks!

**Comment by NotAProton** [comment]
Thanks!

**Comment by Smart123s** [comment]
Thanks for explaining it :)

**Pull request merged**
