### PR TITLE
fix: "Redirect to %" fixed.

### PR DESCRIPTION
**Pull request by ramazansancar**
Fix(es): 

image

- [X] I made sure there are no unnecessary changes in the code;
- [X] Tested on Chromium (Includes Opera, Brave, Vivaldi, Edge, etc);
- [X] Tested on Firefox.

Resolve:
Chrome:
image
Firefox:
image

Fix Source: https://chromium.googlesource.com/chromium/src/+/901414aca5338840519c9fa7ee3fb82cb4f0f18f/chrome/common/extensions/docs/static/i18n.html#303

### CODE REVIEW

**Comment by ramazansancar** [comment]
Translation provided for all languages.
https://github.com/FastForwardTeam/FastForward/pull/1318

**Review by NotAProton — CHANGES_REQUESTED** [review]
Remove the pnpm lock file

**Comment by ramazansancar** [comment]
@NotAProton  Sure :)

**Review by NotAProton — APPROVED** [review]

**Comment by NotAProton** [comment]
Thanks!

**Pull request merged**
