### PR TITLE
Added support for maxurlz.com

### PR DESCRIPTION
**Pull request by Stefanuk12**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: Link to issue

Added a bypass for maxurlz.com. They have a script that creates a button and attaches the href. This simply goes through each script, finding that out and extracting the url via regex.

You can view an example of the source of a link [here](view-source:https://maxurlz.com/Omnisphere2P1) (view-source:https://maxurlz.com/Omnisphere2P1)

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by lostdusty** [comment]
@BS-zombie @reashetyrr

**Comment by reashetyrr** [comment]
sory will check this now

**Comment by reashetyrr** [comment]
it doesnt seem to work for me? the whole script with the required content is not found for me

**Comment by reashetyrr** [comment]
when the script is triggered, the dom that holds the actual script is not loaded in yet

**Review by reashetyrr — APPROVED** [review]
love it, had to put a ensureDomLoaded around it to test it

**Pull request merged**
